using LocalTranslatorApp.Models;

namespace LocalTranslatorApp.Services;

public static class LanguageCatalog
{
    private static readonly LanguageOption AutoDetect = new("Auto", "Detect language", "Automatic", "auto detect", "자동", "언어 감지");

    public static IReadOnlyList<LanguageOption> SourceLanguages =>
        new[] { AutoDetect }.Concat(TargetLanguages).ToArray();

    public static IReadOnlyList<LanguageOption> TargetLanguages { get; } =
    [
        new("Abkhaz"),
        new("Acehnese"),
        new("Acholi"),
        new("Afar"),
        new("Afrikaans"),
        new("Albanian"),
        new("Alur"),
        new("Amharic"),
        new("Arabic", "아랍어"),
        new("Armenian"),
        new("Assamese"),
        new("Avar"),
        new("Awadhi"),
        new("Aymara"),
        new("Azerbaijani"),
        new("Balinese"),
        new("Baluchi"),
        new("Bambara"),
        new("Baoule"),
        new("Bashkir"),
        new("Basque"),
        new("Batak Karo"),
        new("Batak Simalungun"),
        new("Batak Toba"),
        new("Belarusian"),
        new("Bemba"),
        new("Bengali"),
        new("Betawi"),
        new("Bhojpuri"),
        new("Bikol"),
        new("Bosnian"),
        new("Breton"),
        new("Bulgarian"),
        new("Buryat"),
        new("Cantonese"),
        new("Catalan"),
        new("Cebuano"),
        new("Chamorro"),
        new("Chechen"),
        new("Chichewa"),
        new("Chinese", "중국어"),
        new("Chinese (Simplified)", "Simplified Chinese", "중국어 간체", "간체"),
        new("Chinese (Traditional)", "Traditional Chinese", "중국어 번체", "번체"),
        new("Chuukese"),
        new("Chuvash"),
        new("Corsican"),
        new("Crimean Tatar (Cyrillic)"),
        new("Crimean Tatar (Latin)"),
        new("Croatian"),
        new("Czech"),
        new("Danish"),
        new("Dari"),
        new("Dhivehi"),
        new("Dinka"),
        new("Dogri"),
        new("Dombe"),
        new("Dutch"),
        new("Dyula"),
        new("Dzongkha"),
        new("English", "영어"),
        new("Esperanto"),
        new("Estonian"),
        new("Ewe"),
        new("Faroese"),
        new("Fijian"),
        new("Filipino", "Tagalog"),
        new("Finnish"),
        new("Fon"),
        new("French", "프랑스어"),
        new("French (Canada)", "Canadian French"),
        new("Frisian"),
        new("Friulian"),
        new("Fulani"),
        new("Ga"),
        new("Galician"),
        new("Georgian"),
        new("German", "독일어"),
        new("Greek"),
        new("Guarani"),
        new("Gujarati"),
        new("Haitian Creole"),
        new("Hakha Chin"),
        new("Hausa"),
        new("Hawaiian"),
        new("Hebrew"),
        new("Hiligaynon"),
        new("Hindi", "힌디어"),
        new("Hmong"),
        new("Hungarian"),
        new("Hunsrik"),
        new("Iban"),
        new("Icelandic"),
        new("Igbo"),
        new("Ilocano"),
        new("Indonesian"),
        new("Inuktut (Latin)"),
        new("Inuktut (Syllabics)"),
        new("Irish"),
        new("Italian", "이탈리아어"),
        new("Jamaican Patois"),
        new("Japanese", "일본어"),
        new("Javanese"),
        new("Jingpo"),
        new("Kalaallisut"),
        new("Kannada"),
        new("Kanuri"),
        new("Kapampangan"),
        new("Kazakh"),
        new("Khasi"),
        new("Khmer"),
        new("Kiga"),
        new("Kikongo"),
        new("Kinyarwanda"),
        new("Kituba"),
        new("Kokborok"),
        new("Komi"),
        new("Konkani"),
        new("Korean", "한국어", "Korea", "한글"),
        new("Krio"),
        new("Kurdish (Kurmanji)"),
        new("Kurdish (Sorani)"),
        new("Kyrgyz"),
        new("Lao"),
        new("Latgalian"),
        new("Latin"),
        new("Latvian"),
        new("Ligurian"),
        new("Limburgish"),
        new("Lingala"),
        new("Lithuanian"),
        new("Lombard"),
        new("Luganda"),
        new("Luo"),
        new("Luxembourgish"),
        new("Macedonian"),
        new("Madurese"),
        new("Maithili"),
        new("Makassar"),
        new("Malagasy"),
        new("Malay"),
        new("Malay (Jawi)"),
        new("Malayalam"),
        new("Maltese"),
        new("Mam"),
        new("Manx"),
        new("Maori"),
        new("Marathi"),
        new("Marshallese"),
        new("Marwadi"),
        new("Mauritian Creole"),
        new("Meadow Mari"),
        new("Meiteilon (Manipuri)"),
        new("Minang"),
        new("Mizo"),
        new("Mongolian"),
        new("Myanmar (Burmese)"),
        new("Nahuatl"),
        new("Ndebele (South)"),
        new("Nepali"),
        new("NKo"),
        new("Norwegian"),
        new("Nuer"),
        new("Occitan"),
        new("Odia (Oriya)"),
        new("Oromo"),
        new("Ossetian"),
        new("Pangasinan"),
        new("Papiamento"),
        new("Pashto"),
        new("Persian", "Farsi"),
        new("Polish"),
        new("Portuguese (Brazil)", "Brazilian Portuguese"),
        new("Portuguese (Portugal)", "European Portuguese"),
        new("Punjabi (Gurmukhi)"),
        new("Punjabi (Shahmukhi)"),
        new("Quechua"),
        new("Q'eqchi'"),
        new("Romani"),
        new("Romanian"),
        new("Rundi"),
        new("Russian", "러시아어"),
        new("Sami (North)"),
        new("Samoan"),
        new("Sango"),
        new("Sanskrit"),
        new("Santali (Latin)"),
        new("Santali (Ol Chiki)"),
        new("Scots Gaelic"),
        new("Sepedi"),
        new("Serbian"),
        new("Sesotho"),
        new("Seychellois Creole"),
        new("Shan"),
        new("Shona"),
        new("Sicilian"),
        new("Silesian"),
        new("Sindhi"),
        new("Sinhala"),
        new("Slovak"),
        new("Slovenian"),
        new("Somali"),
        new("Spanish", "스페인어"),
        new("Sundanese"),
        new("Susu"),
        new("Swahili"),
        new("Swati"),
        new("Swedish"),
        new("Tahitian"),
        new("Tajik"),
        new("Tamazight"),
        new("Tamazight (Tifinagh)"),
        new("Tamil"),
        new("Tatar"),
        new("Telugu"),
        new("Tetum"),
        new("Thai"),
        new("Tibetan"),
        new("Tigrinya"),
        new("Tiv"),
        new("Tok Pisin"),
        new("Tongan"),
        new("Tshiluba"),
        new("Tsonga"),
        new("Tswana"),
        new("Tulu"),
        new("Tumbuka"),
        new("Turkish"),
        new("Turkmen"),
        new("Tuvan"),
        new("Twi"),
        new("Udmurt"),
        new("Ukrainian"),
        new("Urdu"),
        new("Uyghur"),
        new("Uzbek"),
        new("Venda"),
        new("Venetian"),
        new("Vietnamese"),
        new("Waray"),
        new("Welsh"),
        new("Wolof"),
        new("Xhosa"),
        new("Yakut"),
        new("Yiddish"),
        new("Yoruba"),
        new("Yucatec Maya"),
        new("Zapotec"),
        new("Zulu")
    ];
}
